version: '3'

services:
  backend:
    build: .
    depends_on:
      - database
    environment:
      - PORT=2500
      - MONGODB_CNN=mongodb://database:27017/test
    ports:
      - "2500:2500"
  database:
    image: mongo
    ports:
      - "27017:26017"
